site_url: https://nihongonotes.com
site_name: Nihongo Notes
dev_addr: '127.0.0.1:9000'
nav:
    - Home: index.md
    - Path: path.md
    - Notes:
        - Grammar: notes/grammar.md
        - Kids TV:
            - Peppa Pig: notes/kids-tv/peppa-pig.md
        # - Satori Reader:
        #     - Kiki-Mimi Radio: notes/satori-reader/kiki-mimi-radio.md
        - Music:
            - Kenta Kiritani: notes/music/kenta-kiritani.md
            - Kyu Sakamoto: notes/music/kyu-sakamoto.md
            - マスドレ: notes/music/mass-of-the-fermenting-dregs.md
        - Gaming:
            # - Common Phrases: notes/gaming.md
            - Fortnite: notes/games/fortnite.md
    - Resources: resources.md
    - Kanji:
        - "<span>1st Grade Kanji&nbsp;<mark class=\"cited\">93%</mark></span>": kanji/grade1.md
        - "<span>2nd Grade Kanji&nbsp;<mark class=\"cited\">58%</mark></span>": kanji/grade2.md
        - "<span>3rd Grade Kanji&nbsp;<mark class=\"cited\">31%</mark></span>": kanji/grade3.md
        - "<span>4th Grade Kanji&nbsp;<mark class=\"cited\">21%</mark></span>": kanji/grade4.md
        - "<span>5th Grade Kanji&nbsp;<mark class=\"cited\">14%</mark></span>": kanji/grade5.md
        - "<span>6th Grade Kanji&nbsp;<mark class=\"cited\">9%</mark></span>": kanji/grade6.md
        - "<span>High School Kanji (1/5)&nbsp;<mark class=\"cited\">14%</mark></span>": kanji/grade71.md
        - "<span>High School Kanji (2/5)&nbsp;<mark class=\"cited\">0%</mark></span>": kanji/grade72.md
        - "<span>High School Kanji (3/5)&nbsp;<mark class=\"cited\">1%</mark></span>": kanji/grade73.md
        - "<span>High School Kanji (4/5)&nbsp;<mark class=\"cited\">0%</mark></span>": kanji/grade74.md
        - "<span>High School Kanji (5/5)&nbsp;<mark class=\"cited\">0%</mark></span>": kanji/grade75.md
        - "<span>Other Kanji&nbsp;<mark class=\"cited\">5%</mark></span>": kanji/other.md
        - "<span>Particles</span>": kanji/particles.md
    - About: about.md
theme:
    name: material
    custom_dir: overrides
    language: en
    favicon: images/favicon.png
    logo: images/logo.svg
    font: false
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/extra.js
extra:
    # generator: false
    analytics:
        provider: google
        property: G-Q36HCES7BW
markdown_extensions:
    - meta
    - def_list
    - toc:
        permalink: true
    - attr_list
    - md_in_html
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
watch:
    - includes
plugins:
    - search:
        lang:
            - en
            - ja