site_url: https://nihongonotes.com
site_name: Nihongo Notes
dev_addr: '127.0.0.1:9000'
nav:
    - Home: index.md
    - Immersion: immersion.md
    - Kanji:
        - "<span>1st Grade</span>": kanji/grade1.md
        - "<span>2nd Grade&nbsp;<mark class=\"cited\">82%</mark></span>": kanji/grade2.md
        - "<span>3rd Grade&nbsp;<mark class=\"cited\">48%</mark></span>": kanji/grade3.md
        - "<span>4th Grade&nbsp;<mark class=\"cited\">32%</mark></span>": kanji/grade4.md
        - "<span>5th Grade&nbsp;<mark class=\"cited\">21%</mark></span>": kanji/grade5.md
        - "<span>6th Grade&nbsp;<mark class=\"cited\">21%</mark></span>": kanji/grade6.md
        - "<span>High School (1/5)&nbsp;<mark class=\"cited\">19%</mark></span>": kanji/grade71.md
        - "<span>High School (2/5)&nbsp;<mark class=\"cited\">2%</mark></span>": kanji/grade72.md
        - "<span>High School (3/5)&nbsp;<mark class=\"cited\">3%</mark></span>": kanji/grade73.md
        - "<span>High School (4/5)&nbsp;<mark class=\"cited\">4%</mark></span>": kanji/grade74.md
        - "<span>High School (5/5)&nbsp;<mark class=\"cited\">1%</mark></span>": kanji/grade75.md
        - "<span>Other&nbsp;<mark class=\"cited\">9%</mark></span>": kanji/other.md
        - "<span>Particles</span>": kanji/particles.md
    - Blog:
        - blog/index.md
theme:
    name: material
    custom_dir: overrides
    language: en
    favicon: images/favicon.png
    logo: images/logo.svg
    font: false
    palette:
        primary: custom
        accent: custom
        scheme: custom
    features:
        - search.share
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/extra.js
extra:
    # generator: false
    analytics:
        provider: google
        property: G-Q36HCES7BW
markdown_extensions:
    - meta
    - def_list
    - abbr
    - toc:
        permalink: true
    - attr_list
    - md_in_html
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
watch:
    - includes
plugins:
    - blog
    - glightbox:
        skip_classes:
            - nopop
    - search:
        lang:
            - ja