site_url: https://nihongonotes.com
site_name: Nihongo Notes
nav:
    - Home: index.md
    - Path: path.md
    - Notes:
        - Grammar: notes/grammar.md
        # - Gaming: notes/gaming.md
        # - Steam Games:
        #     - "Alba: A Wildlife Adventure": notes/play/steam/alba-a-wildlife-adventure.md
        - Kids TV:
            - Peppa Pig: notes/watch/kids-tv/peppa-pig.md
        # - Satori Reader:
        #     - Kiki-Mimi Radio: notes/read/satori-reader/kiki-mimi-radio.md
        - Music:
            - Kenta Kiritani: notes/listen/music/kenta-kiritani.md
            - Kyu Sakamoto: notes/listen/music/kyu-sakamoto.md
    - Resources: resources.md
    - Kanji:
        - "<span>1st Grade&nbsp;<mark class=\"cited\">WIP</mark></span>": kanji/grade1.md
        - "<span>2nd Grade&nbsp;<mark class=\"cited\">WIP</mark></span>": kanji/grade2.md
        - "<span>3rd Grade&nbsp;<mark class=\"cited\">WIP</mark></span>": kanji/grade3.md
        - "<span>4th Grade&nbsp;<mark class=\"cited\">WIP</mark></span>": kanji/grade4.md
        - "<span>5th Grade&nbsp;<mark class=\"cited\">WIP</mark></span>": kanji/grade5.md
        - "<span>6th Grade&nbsp;<mark class=\"cited\">WIP</mark></span>": kanji/grade6.md
        - "<span>Secondary School&nbsp;<mark class=\"cited\">WIP</mark></span>": kanji/grade7.md
        - "<span>Other&nbsp;<mark class=\"cited\">WIP</mark></span>": kanji/other.md
        - "<span>Particles&nbsp;<mark class=\"cited\">WIP</mark></span>": kanji/particles.md
    - About: about.md
theme:
    name: material
    custom_dir: overrides
    language: en
    favicon: images/favicon.png
    logo: images/logo.svg
    font: false
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
extra_css:
  - stylesheets/extra.css
extra:
    # generator: false
    analytics:
        provider: google
        property: G-Q36HCES7BW
markdown_extensions:
    - meta
    - def_list
    - toc:
        permalink: true
    - attr_list
    - md_in_html
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
watch:
    - includes
plugins:
    - search:
        lang:
            - en
            - ja