site_url: https://nihongonotes.com
site_name: Nihongo Notes
nav:
    - Home: index.md
    - Log: log.md
    - Path: path.md
    - Resources: resources.md
    - Watch:
        - Kids TV:
            - Peppa Pig: watch/kids-tv/peppa-pig.md
    - Read:
        - Satori Reader:
            - Kiki-Mimi Radio: read/satori-reader/kiki-mimi-radio.md
    - Listen:
        - Music:
            - Kenta Kiritani: listen/music/kenta-kiritani.md
            - Kyu Sakamoto: listen/music/kyu-sakamoto.md
    - Play:
        - Steam:
            - "Alba: A Wildlife Adventure": play/steam/alba-a-wildlife-adventure.md
    - About: about.md
theme:
    name: material
    custom_dir: overrides
    language: en
    favicon: images/favicon.png
    logo: images/logo.svg
    font:
        text: Roboto
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
extra_css:
  - stylesheets/extra.css
extra:
    # generator: false
    analytics:
        provider: google
        property: G-Q36HCES7BW
markdown_extensions:
    - meta
    - toc:
        permalink: true
    - attr_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
watch:
    - includes
plugins:
    - search:
        lang:
            - en
            - ja