site_url: https://nihongonotes.com
site_name: Nihongo Notes
dev_addr: '127.0.0.1:9000'
nav:
    - Home: index.md
    - JLPT:
        - Overview: jlpt.md
        - N5:
            - N5 Grammar: jlpt/n5/grammar.md
            - N5 Vocabulary: jlpt/n5/vocabulary.md
            - N5 Kanji: jlpt/n5/kanji.md
    - Games: games.md
    # - Drama: drama.md
    # - Anime: anime.md
    - YouTube: youtube.md
    # - Manga: manga.md
    # - Novels: novels.md
    - Blog:
        - blog/index.md
    - About: about.md
theme:
    name: material
    custom_dir: overrides
    language: en
    favicon: images/favicon.png
    logo: images/logo.svg
    font: false
    features:
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
  - javascripts/extra.js
extra:
    # generator: false
    analytics:
        provider: google
        property: G-Q36HCES7BW
markdown_extensions:
    - meta
    - def_list
    - toc:
        permalink: true
    - attr_list
    - md_in_html
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight
    - admonition
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.snippets
watch:
    - includes
plugins:
    - blog
    - glightbox:
        skip_classes:
            - nopop
    - search:
        lang:
            - ja